-module(ppm).

-export([write/2]).

%%% write(Name, Image) The image is a list of rows, each row a list of
%%% tuples {R,G,B} where the values are floats from 0 to 1. The image
%%% is written using PMM format P6 and color depth 0-255. This means that
%%% each tuple is written as three bytes.

write(Name, Image) ->
    Height = length(Image),
    Width = length(hd(Image)),
    {ok, Fd} = file:open(Name, [write]),
    io:format(Fd, "P6~n", []),
    io:format(Fd, "#~s~n", ["generated by ppm.erl"]),
    io:format(Fd, "~w ~w~n", [Width, Height]),
    io:format(Fd, "255~n", []),
    rows(Image, Fd),
    file:close(Fd).

rows(Rows, Fd) ->
    lists:foreach(fun(R) -> 
                          Colors = row(R), 
                          io:put_chars(Fd, Colors) 
                  end, Rows).

row(Row) ->
    lists:foldr(fun({R,G,B}, A) -> 
                        %% convert to 0-255
                        [ trunc(R*255), trunc(G*255), trunc(B*255) | A] end, 
                [], Row).   








    
